[run]
init_cmds = [
  ["make", "build-server"],
  ["./bin/rest"]
]
watch_all = true
follow_symlinks = true
watch_dirs = [
  "$WORKDIR/internal",
]
watch_exts = [".go", ".cue"]
ignore_files = []
build_delay = 1500
cmds = [
  ["make", "build-server"],
  ["./bin/rest"]
]